<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Capsule\Manager as Capsule;

class PM2WorkersSeeder extends Seeder
{
    public $command;

    /**
     * Run the database seeds.
     *
     * Seed PM2 workers configuration with all columns
     */
    public function run(): void
    {
        $timestamp = date('Y-m-d H:i:s');

        $workers = [
            [
                // Basic Info
                'name' => 'stream-import-worker',
                'display_name' => 'Stream Import Worker',
                'description' => 'Imports streams from M3U playlists and external sources. Runs daily at 3 AM.',
                'script' => './workers/stream-import-worker.cjs',
                'cwd' => null,
                'args' => null,

                // Execution
                'exec_mode' => 'fork',
                'instances' => 1,
                'max_memory_restart' => '500M',

                // Restart Behavior
                'max_restarts' => 10,
                'min_uptime' => '10s',
                'restart_delay' => 5000,
                'autorestart' => 1,
                'cron_restart' => '0 3 * * *',

                // Logging
                'log_level' => 'warn',
                'error_file' => './storage/logs/pm2-stream-import-error.log',
                'out_file' => './storage/logs/pm2-stream-import-out.log',
                'log_file' => './storage/logs/pm2-stream-import-combined.log',
                'log_date_format' => 'YYYY-MM-DD HH:mm:ss Z',
                'merge_logs' => 1,

                // Environment
                'env_vars' => json_encode(['NODE_ENV' => 'production', 'LOG_LEVEL' => 'warn']),

                // Watch
                'watch' => 0,
                'ignore_watch' => json_encode(['node_modules', 'logs', '*.log', 'storage', 'cache']),

                // Timeouts
                'kill_timeout' => 5000,
                'listen_timeout' => 3000,
                'shutdown_with_message' => 1,

                // Status
                'enabled' => 1,
                'auto_start' => 1,
                'priority' => 10,

                // Categories
                'category' => 'streaming',
                'tags' => json_encode(['import', 'm3u', 'playlists']),

                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'ffprobe-worker',
                'display_name' => 'FFprobe Worker',
                'description' => 'Analyzes stream technical details (codec, bitrate, resolution). Runs in cluster mode with 2 instances.',
                'script' => './workers/ffprobe-worker.cjs',
                'cwd' => null,
                'args' => null,
                'exec_mode' => 'cluster',
                'instances' => 2,
                'max_memory_restart' => '300M',
                'max_restarts' => 10,
                'min_uptime' => '10s',
                'restart_delay' => 5000,
                'autorestart' => 1,
                'cron_restart' => '0 3 * * *',
                'log_level' => 'warn',
                'error_file' => './storage/logs/pm2-ffprobe-error.log',
                'out_file' => './storage/logs/pm2-ffprobe-out.log',
                'log_file' => './storage/logs/pm2-ffprobe-combined.log',
                'log_date_format' => 'YYYY-MM-DD HH:mm:ss Z',
                'merge_logs' => 1,
                'env_vars' => json_encode(['NODE_ENV' => 'production', 'LOG_LEVEL' => 'warn']),
                'watch' => 0,
                'ignore_watch' => json_encode(['node_modules', 'logs', '*.log', 'storage', 'cache']),
                'kill_timeout' => 30000,
                'listen_timeout' => 3000,
                'shutdown_with_message' => 1,
                'enabled' => 1,
                'auto_start' => 1,
                'priority' => 20,
                'category' => 'streaming',
                'tags' => json_encode(['analysis', 'ffprobe', 'technical']),
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'stream-manager-worker',
                'display_name' => 'Stream Manager Worker',
                'description' => 'Manages stream lifecycle (start/stop/restart). Critical for stream operations.',
                'script' => './workers/stream-manager-worker.cjs',
                'cwd' => null,
                'args' => null,
                'exec_mode' => 'fork',
                'instances' => 1,
                'max_memory_restart' => '400M',
                'max_restarts' => 10,
                'min_uptime' => '10s',
                'restart_delay' => 5000,
                'autorestart' => 1,
                'cron_restart' => '0 3 * * *',
                'log_level' => 'warn',
                'error_file' => './storage/logs/pm2-stream-manager-error.log',
                'out_file' => './storage/logs/pm2-stream-manager-out.log',
                'log_file' => './storage/logs/pm2-stream-manager-combined.log',
                'log_date_format' => 'YYYY-MM-DD HH:mm:ss Z',
                'merge_logs' => 1,
                'env_vars' => json_encode(['NODE_ENV' => 'production', 'LOG_LEVEL' => 'warn']),
                'watch' => 0,
                'ignore_watch' => json_encode(['node_modules', 'logs', '*.log', 'storage', 'cache']),
                'kill_timeout' => 10000,
                'listen_timeout' => 3000,
                'shutdown_with_message' => 1,
                'enabled' => 1,
                'auto_start' => 1,
                'priority' => 30,
                'category' => 'streaming',
                'tags' => json_encode(['manager', 'lifecycle', 'critical']),
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'stream-monitor-worker',
                'display_name' => 'Stream Monitor Worker',
                'description' => 'Health checks and logging for active streams. Monitors uptime and performance.',
                'script' => './workers/stream-monitor-worker.cjs',
                'cwd' => null,
                'args' => null,
                'exec_mode' => 'fork',
                'instances' => 1,
                'max_memory_restart' => '300M',
                'max_restarts' => 10,
                'min_uptime' => '10s',
                'restart_delay' => 5000,
                'autorestart' => 1,
                'cron_restart' => '0 3 * * *',
                'log_level' => 'warn',
                'error_file' => './storage/logs/pm2-stream-monitor-error.log',
                'out_file' => './storage/logs/pm2-stream-monitor-out.log',
                'log_file' => './storage/logs/pm2-stream-monitor-combined.log',
                'log_date_format' => 'YYYY-MM-DD HH:mm:ss Z',
                'merge_logs' => 1,
                'env_vars' => json_encode(['NODE_ENV' => 'production', 'LOG_LEVEL' => 'warn']),
                'watch' => 0,
                'ignore_watch' => json_encode(['node_modules', 'logs', '*.log', 'storage', 'cache']),
                'kill_timeout' => 5000,
                'listen_timeout' => 3000,
                'shutdown_with_message' => 1,
                'enabled' => 1,
                'auto_start' => 1,
                'priority' => 40,
                'category' => 'monitoring',
                'tags' => json_encode(['health', 'monitoring', 'logs']),
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'website-health-worker',
                'display_name' => 'Website Health Worker',
                'description' => 'Website uptime monitoring and health checks. Ensures platform availability.',
                'script' => './workers/website-health-worker.cjs',
                'cwd' => null,
                'args' => null,
                'exec_mode' => 'fork',
                'instances' => 1,
                'max_memory_restart' => '200M',
                'max_restarts' => 10,
                'min_uptime' => '10s',
                'restart_delay' => 5000,
                'autorestart' => 1,
                'cron_restart' => '0 3 * * *',
                'log_level' => 'warn',
                'error_file' => './storage/logs/pm2-website-health-error.log',
                'out_file' => './storage/logs/pm2-website-health-out.log',
                'log_file' => './storage/logs/pm2-website-health-combined.log',
                'log_date_format' => 'YYYY-MM-DD HH:mm:ss Z',
                'merge_logs' => 1,
                'env_vars' => json_encode(['NODE_ENV' => 'production', 'LOG_LEVEL' => 'warn']),
                'watch' => 0,
                'ignore_watch' => json_encode(['node_modules', 'logs', '*.log', 'storage', 'cache']),
                'kill_timeout' => 5000,
                'listen_timeout' => 3000,
                'shutdown_with_message' => 1,
                'enabled' => 1,
                'auto_start' => 1,
                'priority' => 50,
                'category' => 'monitoring',
                'tags' => json_encode(['health', 'uptime', 'website']),
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'srt-proxy-worker',
                'display_name' => 'SRT Proxy Worker',
                'description' => 'SRT protocol proxy with AES-256 encryption. No transcoding - secure relay only. Handles device locking and stream monitoring.',
                'script' => './workers/srt-proxy-worker.cjs',
                'cwd' => null,
                'args' => null,
                'exec_mode' => 'fork',
                'instances' => 1,
                'max_memory_restart' => '400M',
                'max_restarts' => 10,
                'min_uptime' => '10s',
                'restart_delay' => 5000,
                'autorestart' => 1,
                'cron_restart' => '0 3 * * *',
                'log_level' => 'warn',
                'error_file' => './storage/logs/pm2-srt-proxy-error.log',
                'out_file' => './storage/logs/pm2-srt-proxy-out.log',
                'log_file' => './storage/logs/pm2-srt-proxy-combined.log',
                'log_date_format' => 'YYYY-MM-DD HH:mm:ss Z',
                'merge_logs' => 1,
                'env_vars' => json_encode(['NODE_ENV' => 'production', 'LOG_LEVEL' => 'warn']),
                'watch' => 0,
                'ignore_watch' => json_encode(['node_modules', 'logs', '*.log', 'storage', 'cache']),
                'kill_timeout' => 10000,
                'listen_timeout' => 3000,
                'shutdown_with_message' => 1,
                'enabled' => 1,
                'auto_start' => 1,
                'priority' => 60,
                'category' => 'proxy',
                'tags' => json_encode(['srt', 'proxy', 'encryption', 'enterprise']),
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'v2ray-proxy-worker',
                'display_name' => 'V2Ray Proxy Worker',
                'description' => 'Traffic obfuscation using V2Ray VMess/VLESS protocols. Bypasses DPI and censorship with WebSocket tunneling and domain fronting.',
                'script' => './workers/v2ray-proxy-worker.cjs',
                'cwd' => null,
                'args' => null,
                'exec_mode' => 'fork',
                'instances' => 1,
                'max_memory_restart' => '500M',
                'max_restarts' => 10,
                'min_uptime' => '10s',
                'restart_delay' => 5000,
                'autorestart' => 1,
                'cron_restart' => '0 3 * * *',
                'log_level' => 'warn',
                'error_file' => './storage/logs/pm2-v2ray-proxy-error.log',
                'out_file' => './storage/logs/pm2-v2ray-proxy-out.log',
                'log_file' => './storage/logs/pm2-v2ray-proxy-combined.log',
                'log_date_format' => 'YYYY-MM-DD HH:mm:ss Z',
                'merge_logs' => 1,
                'env_vars' => json_encode(['NODE_ENV' => 'production', 'LOG_LEVEL' => 'warn']),
                'watch' => 0,
                'ignore_watch' => json_encode(['node_modules', 'logs', '*.log', 'storage', 'cache']),
                'kill_timeout' => 10000,
                'listen_timeout' => 3000,
                'shutdown_with_message' => 1,
                'enabled' => 1,
                'auto_start' => 1,
                'priority' => 70,
                'category' => 'proxy',
                'tags' => json_encode(['v2ray', 'proxy', 'obfuscation', 'enterprise']),
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'quic-proxy-worker',
                'display_name' => 'QUIC/HTTP3 Proxy Worker',
                'description' => 'Next-gen HTTP/3 over QUIC with TLS 1.3 and ECH. 0-RTT connection, improved performance on lossy networks. No transcoding.',
                'script' => './workers/quic-proxy-worker.cjs',
                'cwd' => null,
                'args' => null,
                'exec_mode' => 'fork',
                'instances' => 1,
                'max_memory_restart' => '400M',
                'max_restarts' => 10,
                'min_uptime' => '10s',
                'restart_delay' => 5000,
                'autorestart' => 1,
                'cron_restart' => '0 3 * * *',
                'log_level' => 'warn',
                'error_file' => './storage/logs/pm2-quic-proxy-error.log',
                'out_file' => './storage/logs/pm2-quic-proxy-out.log',
                'log_file' => './storage/logs/pm2-quic-proxy-combined.log',
                'log_date_format' => 'YYYY-MM-DD HH:mm:ss Z',
                'merge_logs' => 1,
                'env_vars' => json_encode(['NODE_ENV' => 'production', 'LOG_LEVEL' => 'warn']),
                'watch' => 0,
                'ignore_watch' => json_encode(['node_modules', 'logs', '*.log', 'storage', 'cache']),
                'kill_timeout' => 10000,
                'listen_timeout' => 3000,
                'shutdown_with_message' => 1,
                'enabled' => 1,
                'auto_start' => 1,
                'priority' => 80,
                'category' => 'proxy',
                'tags' => json_encode(['quic', 'http3', 'proxy', 'enterprise']),
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
        ];

        // Truncate existing workers
        Capsule::table('pm2_workers')->truncate();

        // Insert all workers
        foreach ($workers as $worker) {
            Capsule::table('pm2_workers')->insert($worker);
        }

        if ($this->command) {
            $this->command->info('PM2 workers seeded successfully with all ' . count($workers) . ' workers!');
        }
    }
}
