[global]
pid = /home/casapu/projects/FOS-Streaming-v69/fospackv69/fos/php/php-fpm-streaming.pid
error_log = /home/casapu/projects/FOS-Streaming-v69/fospackv69/fos/logs/php-fpm-streaming-error.log
log_level = warning
daemonize = yes

include = /home/casapu/projects/FOS-Streaming-v69/fospackv69/fos/php/etc/pool.d-streaming/*.conf
