[streaming]
user = casapu
group = casapu
listen = /home/casapu/projects/FOS-Streaming-v69/fospackv69/fos/php/php-fpm-streaming.socket
listen.owner = casapu
listen.group = casapu
listen.mode = 0660
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
pm.max_requests = 500
request_terminate_timeout = 30s
slowlog = /home/casapu/projects/FOS-Streaming-v69/fospackv69/fos/logs/php-fpm-streaming-slow.log
catch_workers_output = yes
security.limit_extensions = .php
